<MyScreenView>:
    # Will always be at the bottom of the screen.
    MDBottomAppBar:

        MDToolbar:
            title: "WOT"
            type: "bottom"

            right_action_items: [["gamepad", lambda x: root.play()], ["accounts", lambda x: root.open_dialog(mode="account")]]
            left_action_items: [["border-color", lambda x: root.open_dialog(mode="rename")], ["money", lambda x: root.buy()]]

